apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: demo-app
  spec:
    finalizers:
    - kubernetes
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: spring-petclinic http port.
    labels:
      app: spring-petclinic
      app.kubernetes.io/component: spring-petclinic
      app.kubernetes.io/instance: spring-petclinic
      application: spring-petclinic
    name: spring-petclinic
  spec:
    ports:
      - port: 8080
        targetPort: 8080
    selector:
      deploymentConfig: spring-petclinic
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      description: Route for spring-petclinic http service.
    labels:
      app: spring-petclinic
      app.kubernetes.io/component: spring-petclinic
      app.kubernetes.io/instance: spring-petclinic
      application: spring-petclinic
    name: spring-petclinic
  spec:
    to:
      kind: Service
      name: spring-petclinic
    tls:
      termination: edge
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations: {}
    labels:
      app: spring-petclinic
      app.kubernetes.io/component: spring-petclinic
      app.kubernetes.io/instance: spring-petclinic
      application: spring-petclinic
    name: spring-petclinic
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: spring-petclinic
      application: spring-petclinic
    name: spring-petclinic
  spec:
    successfulBuildsHistoryLimit: 2
    failedBuildsHistoryLimit: 2
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: spring-petclinic:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/spring-projects/spring-petclinic.git
      type: Git
    strategy:
      sourceStrategy:
        forcePull: true
        from:
          kind: ImageStreamTag
          name: java:8
          namespace: openshift
      type: Source
    triggers:
      - imageChange: {}
        type: ImageChange
      - type: ConfigChange
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: spring-petclinic
      app.kubernetes.io/component: spring-petclinic
      app.kubernetes.io/instance: spring-petclinic
      application: spring-petclinic
    name: spring-petclinic
  spec:
    replicas: 1
    selector:
      matchLabels:
        deploymentConfig: spring-petclinic
    strategy:
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          application: spring-petclinic
          deploymentConfig: spring-petclinic
        name: spring-petclinic
      spec:
        containers:
          - imagePullPolicy: Always
            image: image-registry.openshift-image-registry.svc:5000/demo-app/spring-petclinic:latest
            name: spring-petclinic
            resources:
              limits:
                cpu: 200m
                memory: 750Mi
              requests:
                cpu: 100m
                memory: 500Mi
            ports:
              - containerPort: 8080
                name: http
                protocol: TCP
              - containerPort: 8443
                name: https
                protocol: TCP
        terminationGracePeriodSeconds: 150
