apiVersion: v1
kind: List
items:
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    name: demo-project
    namespace: argocd
  spec:
    description: demo-project
    destinations:
      - namespace: demo-app
        server: 'https://kubernetes.default.svc'
      - namespace: demo-pipeline
        server: 'https://kubernetes.default.svc'
    sourceRepos:
      - 'https://github.com/rpalstra/argocd-demo.git'
    clusterResourceWhitelist:
      - group: ''
        kind: Namespace
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: demo-app
    namespace: argocd
  spec:
    destination:
      namespace: demo-app
      server: 'https://kubernetes.default.svc'
    source:
      path: 'demo-app'
      repoURL: 'https://github.com/rpalstra/argocd-demo.git'
      targetRevision: HEAD
      directory:
        recurse: true
    project: demo-project
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: demo-pipeline
    namespace: argocd
  spec:
    destination:
      namespace: demo-pipeline
      server: 'https://kubernetes.default.svc'
    source:
      path: 'demo-pipeline'
      repoURL: 'https://github.com/rpalstra/argocd-demo.git'
      targetRevision: HEAD
      directory:
        recurse: true
    project: demo-project
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: tekton
    namespace: argocd
  spec:
    project: default
    source:
      repoURL: 'https://github.com/rpalstra/argocd-demo.git'
      path: tekton
      targetRevision: HEAD
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: openshift-operators
